# Generated by Django 6.0.4 on 2026-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_role_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='join_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
