# Generated by Django 6.0.4 on 2026-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizationjoinrequest_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color like #0d6efd', max_length=20, null=True),
        ),
    ]
