# Generated by Django 6.0.4 on 2026-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('small', 'Small Group')], default='small', max_length=20),
        ),
    ]
