# Generated by Django 6.0.4 on 2026-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_group_group_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='grouppost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
