# Generated by Django 6.0.4 on 2026-04-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_role_organization_is_active_and_more'),
        ('engagement', '0003_alter_grouppost_options_grouppost_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_type',
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
