# Generated by Django 6.0.2 on 2026-04-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_grouppost_postreply_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Church Group', 'verbose_name_plural': 'Church Groups'},
        ),
    ]
