# Generated by Django 6.0.4 on 2026-04-28 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_alter_group_options_remove_group_group_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='groupinvitation',
            constraint=models.UniqueConstraint(fields=('group', 'invited_user'), name='unique_group_invite'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_group_member'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_like'),
        ),
    ]
