# Generated by Django 6.0.2 on 2026-04-17 09:28

import engagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_grouppost_postreply_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Church Group', 'verbose_name_plural': 'Church Groups'},
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', validators=[engagement.models.validate_file_size]),
        ),
    ]
