# Generated by Django 6.0.2 on 2026-04-14 04:07

import engagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', validators=[engagement.models.validate_file_size]),
        ),
    ]
