# Generated by Django 6.0.4 on 2026-05-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_alter_groupinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
    ]
