# Generated by Django 6.0.4 on 2026-05-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_devotional_organization_media_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
