# Generated by Django 6.0.2 on 2026-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.RenameField(
            model_name='media',
            old_name='is_active',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='media',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='media',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
