# Generated by Django 6.1 on 2026-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_churchupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='teachings/audio/'),
        ),
    ]
