# Generated by Django 6.0.2 on 2026-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_media_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
