# Generated by Django 6.1 on 2026-08-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teaching_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='content',
        ),
        migrations.CreateModel(
            name='TeachingAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='teachings/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_audio', to='content.language')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_versions', to='content.teaching')),
            ],
        ),
    ]
