# Generated by Django 6.1 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_language_remove_teaching_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
