# Generated by Django 6.0.2 on 2026-04-14 03:55

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_devotional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', validators=[content.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[content.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', validators=[content.models.validate_file_size]),
        ),
    ]
