# Generated by Django 6.1 on 2026-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_teaching_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='member_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of members in this church'),
        ),
    ]
