# Generated by Django 6.1 on 2026-09-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_church_member_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_baptized', models.PositiveIntegerField(default=1, help_text='Number of people baptized at this event')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this baptism event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptisms', to='content.church')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
