# Generated by Django 6.0.2 on 2026-04-21 07:35

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_media_image_alter_media_upload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/', validators=[content.models.validate_file_size]),
        ),
    ]
