# Generated by Django 6.1 on 2026-09-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_baptism'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of this teaching within its series.', null=True),
        ),
    ]
