# Generated by Django 6.1 on 2026-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_ellenbarrieupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ellenbarrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Ellenbarrie Children's Home", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='ellenbarrie/')),
            ],
        ),
    ]
